#include <string.h>
#include <assert.h>

#include "configuration.h"
#include "main.h"
#include "MeshService.h"

#include <WiFi.h>

#include "NyanModule.h"
#include "NyanNMEA.h"
#include "NyanVessel.h"
#include "wind.h"

#include "mesh/NodeDB.h"
#include "gps/RTC.h"

#include "os_status.h"

// Vessel data acquired from local NMEA network
//NyanVessel v_nmea;

// Data from Nyan device sensors
//NyanVessel v_local;

NyanVessel v;

/*
  Need running average and max over last reporting period - 10 mins seems to be a standard.

  First do a three second running average, then take the max and mean of
  that. This was the storage is bounded. Don't need more detail than three
  seconds.
*/

/* Weather station reporting period in seconds. */
constexpr uint16_t met_reporting_period = 600;


/* Import NMEA0183 data from a tcp server.
   If not connected, connect.
   Read and parse sentences.
   Add data to ship data model.
*/
void NMEA_read() {
  tNMEA0183Msg NMEA0183Msg;
  tNMEA0183 NMEA0183;
  static WiFiClient tcp;

  const uint8_t NMEA_BUFFER_LENGTH = 85;
  // Including terminating charaters (CR LF)
  const uint8_t NMEA_MIN_SENTENCE_LENGTH = 11;

  static char nmea_buffer[NMEA_BUFFER_LENGTH];
  static uint8_t nmea_index = 0;

  const uint16_t port = 10110;
  const char * host = "209.16.157.57";

  if (!WiFi.isConnected()) {
    LOG_INFO("WiFi not connected\n");
    return;
  }

  if (! tcp.connected()) {
    LOG_WARN("TCP not connected\n");
    if (tcp.connect(host, port)) {
      LOG_INFO("TCP connected\n");
    } else {
      LOG_WARN("Connecting TCP NMEA failed.\n");
      return;
    }
  }

  /* Read and parse NMEA sentences. */
  constexpr uint32_t time_limit = 500; // mS
  uint32_t end_time = millis() + time_limit;
  while (tcp.available() && millis() < end_time) {
    nmea_buffer[nmea_index] = static_cast<char>(tcp.read());

    // There should be no null chars
    if (nmea_buffer[nmea_index] == 0) goto err;

    // Buffer is full and string not finished.
    if (nmea_index == NMEA_BUFFER_LENGTH - 1) goto err;

    // When LF encountered, string is finished.
    if (nmea_buffer[nmea_index] == 0x0a) {
      if ((nmea_index >= NMEA_MIN_SENTENCE_LENGTH) &&
          ((nmea_buffer[0] == '$') || (nmea_buffer[0] == '!')) &&
          // Check for CR
          (nmea_buffer[nmea_index-1] == 0x0d)) {

        // null terminate, to treat as string
        nmea_buffer[nmea_index-1] = 0;
        parse_sentence(nmea_buffer);
      }
      goto done;
    }

    // Move on and loop for next char
    nmea_index++;
    continue;

  err:
    LOG_DEBUG(" NMEA parse error\n");
  done:
    nmea_index = 0;
  }
}

bool get_local_GPS(NyanVessel& v) {
  // FIXME: validity period will be longer than specified. Should call this
  // funcion when GPS supplies a fix.

  // Is it seconds or mS?
  uint32_t validity_period = 10;

  if ((localPosition.timestamp > 0) &&
      ((localPosition.timestamp + validity_period) > getValidTime(RTCQualityFromNet)) &&
      (localPosition.fix_quality > 0)) {
    v.COG.set(localPosition.ground_track * 100);
    v.SOG.set(localPosition.ground_speed * MPS_TO_KNOTS);
    LOG_DEBUG("Got fix from local GPS. SOG %f COG %f\n",
              v.SOG.get(), v.COG.get());
    return true;
  }
  return false;
}

void sample_NMEA_sensors(NyanVessel& v) {
  v.HDT.sample();
  v.AWA.sample();
  v.AWS.sample();
  LOG_DEBUG("Sensors after sampling: HDT: %f AWA (av): %f (%f) AWS (av) : %f %f\n",
            v.HDT.get(), v.AWA.raw(), v.AWA.get(),
            v.AWS.raw(), v.AWS.get());

  double GWS, GWD;
  if (Wind::derive_ground_wind(v, GWS, GWD)) {
    v.GWS.stats.sample(GWS);
    v.GWD.stats.sample(GWD);
  }
}

/* Periodically send ship data over mesh. */

/* Can run every time the thread is scheduled.
   Delayed to meet desired period, which is the return value.
*/
int32_t NyanModule::runOnce() {
  NMEA_read();
  sample_NMEA_sensors(v);
  get_local_GPS(v);

  send_report();

  LOG_INFO("No of tasks: %u\n", task_count());

  return 3000; // period in milliseconds
}

void NyanModule::send_report() {
  /* A struct generated by protobuf definition. */
  nyan_telemetry telemetry;

  // We have data to send
  bool send = false;

  // TODO check protobuf optionalness for what sending when value not available

  if (v.GWS.stats.quality() > 0) {
    send = true;
    telemetry.GWS_mean = (uint8_t) v.GWS.stats.mean();
    telemetry.GWS_gust = v.GWS.stats.max();

    telemetry.GWD_mean = (uint16_t) v.GWD.stats.mean();

    LOG_DEBUG("Sending Ground Wind %i kts, %i°T Gust: %i kts\n",
              telemetry.GWS_mean, telemetry.GWD_mean, telemetry.GWS_gust);
  }

  if (v.water_temperature.valid()) {
    send = true;
    telemetry.water_temperature = v.water_temperature.get();
    LOG_DEBUG("Water temperature %f°C", telemetry.water_temperature);
  }

  if (v.water_depth.valid()) {
    send = true;
    telemetry.water_depth = v.water_depth.get();
    LOG_DEBUG("Sending water depth %fm", telemetry.water_depth);
  }

  if (send) {
    LOG_INFO("Sending Nyan telemetry\n");

    meshtastic_MeshPacket *p = allocDataProtobuf(telemetry);
    p->decoded.want_response = false;
    p->priority = meshtastic_MeshPacket_Priority_RELIABLE;
    service.sendToMesh(p);
  } else {
    LOG_INFO("No valid data to report\n");
  }
}

bool NyanModule::handleReceivedProtobuf(const meshtastic_MeshPacket &mp,
                                        nyan_telemetry *telemetry) {
  if (telemetry == NULL) {
    LOG_WARN("handleReceivedProtobuf() got null protobuf decode\n");
    return false;
  }

  screen->print("Nyan RXed ");

  LOG_DEBUG("handleReceivedProtobuf() called. "
            "Got GWS_mean: %u, GWS_gust: %u, GWD_mean: %u\n",
            telemetry->GWS_mean,
            telemetry->GWS_gust,
            telemetry->GWD_mean);

  return true;
}
