#include "NyanModule.h"
#include "MeshService.h"
#include "configuration.h"
#include "main.h"

#include <assert.h>

/* Connect by tcp to an NMEA0183 data source. */

/* If not connected, connect.
   Read sentence.
   NMEA Parse.
   Add data to ship data model.
*/

/* Periodically send ship data over mesh. */

/* Can run every time the thread is scheduled.
   Delayed to meet desired period, which is the return value.
*/
int32_t NyanModule::runOnce() {
  send_report();

  return 20000; // period in milliseconds
}

void NyanModule::send_report() {
  /* A struct generated by protobuf definition. */
  nyan_telemetry telemetry;

  telemetry.GWS_mean = 15;
  telemetry.GWS_gust = 20;
  telemetry.GWD_mean = 70;

  meshtastic_MeshPacket *p = allocDataProtobuf(telemetry);
  //  p->to = dest;

  p->decoded.want_response = false; // is this needed or default?
  p->priority = meshtastic_MeshPacket_Priority_RELIABLE;

  LOG_INFO("Sending Nyan telemetry");

  service.sendToMesh(p);
}

bool NyanModule::handleReceivedProtobuf(const meshtastic_MeshPacket &mp,
                                        nyan_telemetry *telemetry) {
  if (telemetry == NULL) {
    LOG_WARN("handleReceivedProtobuf() got null protobuf decode");
    return false;
  }

  screen->print("Nyan RXed ");

  LOG_DEBUG("handleReceivedProtobuf() called. "
            "Got GWS_mean: %u, GWS_gust: %u, GWD_mean: %u",
            telemetry->GWS_mean,
            telemetry->GWS_gust,
            telemetry->GWD_mean);

  return true;
}
