#include <string.h>
#include <assert.h>

#include "configuration.h"
#include "main.h"
#include "MeshService.h"

#include <WiFi.h>

#include "NyanModule.h"
#include "NyanNMEA.h"
#include "NyanVessel.h"
#include "wind.h"

#include "mesh/NodeDB.h"
#include "gps/RTC.h"

#include "os_status.h"

NyanVessel v;

/* Import NMEA0183 data from a tcp server.

   If not connected, connect.
   Read and parse sentences.
   Add data to ship data model.
*/
void NMEA_read() {
  tNMEA0183Msg NMEA0183Msg;
  tNMEA0183 NMEA0183;
  static WiFiClient tcp;

  const uint8_t NMEA_BUFFER_LENGTH = 85;
  // Including terminating charaters (CR LF)
  const uint8_t NMEA_MIN_SENTENCE_LENGTH = 11;

  static char nmea_buffer[NMEA_BUFFER_LENGTH];
  static uint8_t nmea_index = 0;

  const uint16_t port = 10110;
  const char * host = "209.16.157.57";

  if (!WiFi.isConnected()) {
    LOG_INFO("WiFi not connected");
    return;
  }

  if (! tcp.connected()) {
    LOG_WARN("TCP not connected\n");
    if (tcp.connect(host, port)) {
      LOG_INFO("TCP connected\n");
    } else {
      LOG_WARN("Connecting TCP NMEA failed.\n");
      return;
    }
  }

  /* Read and parse NMEA sentences. */
  constexpr uint32_t time_limit = 500; // mS
  uint32_t end_time = millis() + time_limit;
  while (tcp.available() && millis() < end_time) {
    nmea_buffer[nmea_index] = static_cast<char>(tcp.read());

    // There should be no null chars
    if (nmea_buffer[nmea_index] == 0) goto reset;

    // Buffer is full and string not finished.
    if (nmea_index == NMEA_BUFFER_LENGTH - 1) goto reset;

    // When LF encountered, string is finished.
    if (nmea_buffer[nmea_index] == 0x0a) {
      if ((nmea_index >= NMEA_MIN_SENTENCE_LENGTH) &&
          ((nmea_buffer[0] == '$') || (nmea_buffer[0] == '!')) &&
          // Check for CR
          (nmea_buffer[nmea_index-1] == 0x0d)) {

        // null terminate, to treat as string
        nmea_buffer[nmea_index-1] = 0;
        parse_sentence(nmea_buffer);
      }
      goto reset;
    }

    // Move on and loop for next char
    nmea_index++;
    continue;

  reset:
    nmea_index = 0;
    LOG_DEBUG(" NMEA restart\n");
  }
}

bool get_ground_wind(double& GWS, double& GWD) {
  uint32_t rtc_sec = getValidTime(RTCQuality::RTCQualityDevice);
  if (rtc_sec < 1) {
    return false;
  }

  uint32_t recent = rtc_sec - 10;
  if (v.meshtastic_position_ts > recent &&
      v.HDT_ts > recent &&
      v.AWA_ts > recent &&
      v.AWS_ts > recent) {

    vec gw = wind::ground_wind(v.AWD(), v.AWS, v.meshtastic_COG, v.meshtastic_SOG);
    GWS = gw.magnitude();
    GWD = gw.angle();
    return true;
  }
  return false;
}

bool get_local_GPS() {
  if (localPosition.fix_quality <= 0) {
    return false;
  }

  v.meshtastic_COG = localPosition.ground_track * 100;
  v.meshtastic_SOG = localPosition.ground_speed * MPS_TO_KNOTS;
  v.meshtastic_position_ts = localPosition.timestamp;

  LOG_DEBUG("Got fix from local GPS. SOG %f COG %f",
            v.meshtastic_SOG, v.meshtastic_COG);

  return true;
}

/* Periodically send ship data over mesh. */

/* Can run every time the thread is scheduled.
   Delayed to meet desired period, which is the return value.
*/
int32_t NyanModule::runOnce() {
  NMEA_read();
  send_report();

  LOG_INFO("No of tasks: %u\n", task_count());

  return 3000; // period in milliseconds
}

void NyanModule::send_report() {
  /* A struct generated by protobuf definition. */
  nyan_telemetry telemetry;
  double GWS, GWD;

  if (! get_local_GPS()) {
    return;
  }

  if (! get_ground_wind(GWS, GWD)) {
    return;
  }

  telemetry.GWS_mean = (uint8_t) GWS;
  //telemetry.GWS_gust = 20;
  telemetry.GWD_mean = (uint16_t) GWD;
  LOG_DEBUG("Got GWS: %i GWD: %i", telemetry.GWS_mean, telemetry.GWD_mean);

  meshtastic_MeshPacket *p = allocDataProtobuf(telemetry);

  p->decoded.want_response = false; // is this needed or default?
  p->priority = meshtastic_MeshPacket_Priority_RELIABLE;

  LOG_INFO("Sending Nyan telemetry");

  service.sendToMesh(p);
}

bool NyanModule::handleReceivedProtobuf(const meshtastic_MeshPacket &mp,
                                        nyan_telemetry *telemetry) {
  if (telemetry == NULL) {
    LOG_WARN("handleReceivedProtobuf() got null protobuf decode");
    return false;
  }

  screen->print("Nyan RXed ");

  LOG_DEBUG("handleReceivedProtobuf() called. "
            "Got GWS_mean: %u, GWS_gust: %u, GWD_mean: %u",
            telemetry->GWS_mean,
            telemetry->GWS_gust,
            telemetry->GWD_mean);

  return true;
}
